apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: rps-sample
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rps-sample
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: rps
      targetAverageValue: 10