apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: externalmetrics.azure.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: azure.com
  versions: 
    - name: v1alpha2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                azure:
                  type: object
                  properties:                     
                    resourceGroup:
                      type: string
                    resourceName:
                      type: string
                    resourceProviderNamespace:
                      type: string
                    resourceType:
                      type: string
                metric:
                  type: object
                  properties: 
                    metricName: 
                      type: string
                    aggregation: 
                      type: string
                    filter: 
                      type: string
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: externalmetrics
    singular: externalmetric
    kind: ExternalMetric
    shortNames:
    - aem
    
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: custommetrics.azure.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: azure.com
  versions: 
    - name: v1alpha2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                metric:
                  type: object
                  properties:
                    metricName:
                      type: string
                    applicationID:
                      type: string
                    query:
                      type: string
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: custommetrics
    singular: custommetric
    kind: CustomMetric
    shortNames:
    - acm
